spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://${url}:3307/practice?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

