spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://localhost:3306/practice?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: bundo
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

