spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://localhost:3306/practice?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

