spring:
  application:
    name: board
  datasource:
    url: jdbc:postgresql://postgres:5432/practice?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

