name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: chmod
      run: chmod 744 gradlew
      # if: runner.os == 'Linux' || runner.os == 'macOS'
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    # - name: CD with Project
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.SSH_KEY }}
    #     port: 22
    #     script: |
    #         cd ci-server
    #         git pull
    #         cd build/libs
    #         java -jar -Dspring.profiles.active=prod board-0.0.1-SNAPSHOT.jar
    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.10.0
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.KEY }}
    - name: Deploy to GCP Compute Engine
      run: |
        gcloud compute ssh ${{ secrets.GCE_INSTANCE_NAME }} \
          --project=${{ secrets.PROJECT_ID }} \
          --zone=${{ secrets.GCE_ZONE }} \
          --command="sudo pkill -f 'java -jar' || true; cd /path/to/your/app && git pull && ./gradlew build && nohup java -jar build/libs/board-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod &"

    
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
